### ISSUE TITLE
Sioyek

### ISSUE THREAD

**Issue by euglevi** [f3fora/nvim-texlabconfig#11]
First of all, thank you for the plugin: very helpful.

If you want to add instructions for Sioyek, the required configuration within the texlab lsp-config forwardSearch is simply:

```
executable = 'sioyek' ,
args = {'--reuse-instance', "--inverse-search", [[nvim-texlabconfig -file %1 -line %2]], "--forward-search-file", "%f", "--forward-search-line", "%l", "%p"}
```

**Comment by euglevi** [comment]
I just saw your commit, that was fast! I just want to point out that in Sioyek you do not need to put the name of the file in quotes, so it is %1 not '%1'. Apparently, Sioyek already does it when passing the variable.

**Comment by f3fora** [comment]
Thanks
