### ISSUE TITLE
Callback for inverse search missing

### ISSUE THREAD

**Issue by GrizzlT** [f3fora/nvim-texlabconfig#13]
Hi, I really like this project.

Something I'm missing though is being able to automatically refocus my terminal when I jump from my pdf viewer (Skim on MacOS) to neovim.

I tried doing so using the `reverse_search_edit_cmd` config option as a sort of "callback".
It seems however that my custom function doesn't get called when performing the inverse search. Any ideas why?

Might it also be an idea to provide a dedicated `after_search_finish` callback in the config instead of me hacking with the edit command?

**Comment by f3fora** [comment]
This is a bug. Thanks for reporting it.
`reverse_search_edit_cmd` does not work and should be the one to use as a callback.

**Comment by f3fora** [comment]
> This is a bug. Thanks for reporting it. `reverse_search_edit_cmd` does not work and should be the one to use as a callback.

I forgot how that command works.

Now I add two callbacks options

**Comment by f3fora** [comment]
Try it and say if it is ok and feel free to share your callbacks

**Comment by GrizzlT** [comment]
Works like a charm! Thanks a lot!

I used the callback described in [this article](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader/#refocus-nvim-macos-inverse).

For my case with Skim and MacOS, my config currently reads:
```lua
require('texlabconfig').setup({
  reverse_search_end_cmd = function ()
    vim.cmd([[
      silent execute "!open -a iTerm"
      redraw!
    ]])
  end
})
```
