### ISSUE TITLE
Inverse search opening file in wrong neovim instance

### ISSUE THREAD

**Issue by sdahdah** [f3fora/nvim-texlabconfig#14]
Thanks for writing this plugin, it's a huge time-saver!

I've run into an issue though. If I have two TeX files open in two different Neovim instances with their corresponding PDFs open in Zathura, inverse searching from both Zathura instances will try to open the file in the most recently opened Neovim instance.

I tried looking through the plugin source, but I don't see a place where all the open Neovim instances are searched for the appropriate buffer.

Am I doing something wrong here?

---

Minimal `init.vim`:

```vim
" Plugin manager
call plug#begin(stdpath('data') . '/plugged')
Plug 'f3fora/nvim-texlabconfig', {'do': 'go build'}

" Set up texlabconfig
lua << EOF
require('texlabconfig').setup({})
EOF

" Configure texlab
lua << EOF
local texexecutable = 'zathura'
local texargs = {
    '--synctex-editor-command',
    [[/home/steven/.local/share/nvim/plugged/nvim-texlabconfig/nvim-texlabconfig -file '%{input}' -line %{line}]],
    '--synctex-forward',
    '%l:1:%f',
    '%p',
}
local servers = {'texlab'}
for _, lsp in pairs(servers) do
  require('lspconfig')[lsp].setup {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    },
    settings = {
        texlab = {
            bibtexFormatter = "texlab",
            build = {
                forwardSearchAfter = false,
                onSave = true,
            },
            chktex = {
                onOpenAndSave = true,
            },
            diagnosticsDelay = 300,
            diagnostics = {
                ignoredPatterns = {"You should not use punctuation in front of quotes"},
            },
            formatterLineLength = 80,
            forwardSearch = {
                executable = texexecutable,
                args = texargs,
            },
            latexFormatter = "latexindent",
            latexindent = {
              modifyLineBreaks = false,
            }
        },
    },
  }
end
EOF
```

**Comment by f3fora** [comment]
This plugin is pretty simple. The behavior described is the one I expected. I understand however it is not optimal. I will try to improve this when I have time.

**Comment by sdahdah** [comment]
Thanks for the quick answer! I threw together a workaround for myself here: https://github.com/sdahdah/nvim-texlabconfig/commit/aa82339298c999b7dd334e58f1616faedb172c13

I don't know `go` at all, so it's not pretty. But is something like that interesting to you? It requires this in `init.vim`:

```vim
local texargs = {
    '--synctex-editor-command',
    [[nvim-texlabconfig -server ]] .. vim.api.nvim_get_vvar('servername') .. [[ -file '%{input}' -line %{line}]],
    '--synctex-forward',
    '%l:1:%f',
    '%p',
}
```

First, the program tries to open the specified server, then it defaults to looking through the cache.

**Comment by f3fora** [comment]
That seems good to me. Would you like to open a PR?
