### ISSUE TITLE
I do not know why but I have to use `%%%` to escape the `%` character in the config file for the inverse search to work properly

### ISSUE THREAD

**Issue by amalgame21** [f3fora/nvim-texlabconfig#17]
I am using zathura.
Instead of this in the config file:
```sh
[[nvim-texlabconfig -file '%{input}' -line %{line} -server ]] .. vim.v.servername,
```
I have to use this:
```sh
[[nvim-texlabconfig -file '%%%{input}' -line %%%{line} -server ]] .. vim.v.servername,
```
so that the command `pgrep -a zathura` display:
`zathura --synctex-editor-command nvim-texlabconfig -file '%{input}' -line %{line}  -server /run/user/1000/nvim.XXXXXX.0 ......` 
instead of:
`zathura --synctex-editor-command nvim-texlabconfig -file '{input}' -line {line} -server /run/user/1000/nvim.XXXXXX.0 ......`
where the inverse search is not working.

I am using `lazy.nvim` instead of `packer.nvim` as the plugin manager, I do not know if it have something to do with this issue.

btw, the line `run = 'go build'` have to be modified as `build = 'go build'` when `lazy.nvim` is used.

**Comment by f3fora** [comment]
In the last weeks, I had some issue too.Thanks to spot the error. 
The same solution can be applied to Sioyek:  `[[nvim-texlabconfig -file %%%1 -line %%%2 -server ]] .. vim.v.servername,`
Do you want to open a PR?

I cannot test Skim, but I think is not necessary, because it is set in preference.
