### ISSUE TITLE
TexlabInverseSearch does nothing with Skim.app

### ISSUE THREAD

**Issue by nalzok** [f3fora/nvim-texlabconfig#2]
This issue is cross-posted in https://github.com/latex-lsp/texlab/issues/583.

Not sure what's going on, but the TexlabInverseSearch command doesn't work for me. I assume executing the following command in Bash should move the cursor to the 8th line of the file `/tmp/test/main.tex`? Nothing happens in my case.

```bash
nvim --headless -c "TexlabInverseSearch '/tmp/test/main.tex' 8"
```

I have the following lines in `init.lua`

```lua
    use 'neovim/nvim-lspconfig' -- Collection of configurations for built-in LSP client
    use 'williamboman/nvim-lsp-installer'
    use 'f3fora/nvim-texlabconfig'

...

    elseif server.name == "texlab" then
      opts.settings = {
        texlab = {
          build = {
            args = {"-X", "compile", "%f", "--synctex", "--keep-logs", "--keep-intermediates"},
            executable = "tectonic",
            forwardSearchAfter = true,
            onSave = true,
          },
          chktex = {
            onEdit = true,
            onOpenAndSave = true,
          },
          forwardSearch = {
            executable = "/Applications/Skim.app/Contents/SharedSupport/displayline",
            args = {"%l", "%p", "%f"},
          }
        }
      }
    end
```

For what it's worth, here is my Skim.app setting

<img width="610" alt="Screen Shot 2022-03-21 at 14 45 32" src="https://user-images.githubusercontent.com/13443062/159351925-82fa3297-a7f6-4e83-93de-e57377add51a.png">

**Comment by mathjiajia** [comment]
I can confirm that the default setting works well on my Mac.
I am using `latexmk`, the others are the same as yours.
Oh, I only used `cmd` + `shift` + `click` to perform the inverse-search.

**Comment by nalzok** [comment]
I have done some investigation myself, and it seems that `cache:servernames()` returns an empty table, which is in turn because the file `cache.fname = $HOME/.cache/nvim/nvim-texlabconfig.json` doesn't exist.

I have another Neovim instance running in another terminal session, where the open buffer contains the file `/tmp/test/main.tex`. It should be able to find that instance, right?

---

I noticed that the README.md says I should use the following configuration instead of a simple `use 'f3fora/nvim-texlabconfig'`

```lua
    use { 'f3fora/nvim-texlabconfig',
          config = function()
            require('texlabconfig').setup()
          end,
          ft = { 'tex', 'bib' },
          cmd = { 'TexlabInverseSearch' },
    }
```

With that change, I am now getting this error

```
packer.nvim: Error running config for nvim-texlabconfig: .../packer/opt/nvim-texlabconfig/lua/texlabconfig/cache.lua:82: attempt to ca
ll upvalue 'create_augroup' (a nil value)
```

I tried `:lua print(vim.api.nvim_create_augroup)`, and it indeed gives me `nil`, which seems strange because I have the latest version of Neovim

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by macports@Mac.internal.macports.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/local/share/nvim"

Run :checkhealth for more info
```

**Comment by nalzok** [comment]
Oh, wait. Just noticed that this plugin requires `nvim 0.7+`. That's probably why it doesn't work. Closing...
