### ISSUE TITLE
[Maybe bug?] No `nvim-texlabconfig.json` in `~/.cache/nvim`

### ISSUE THREAD

**Issue by LC0117** [f3fora/nvim-texlabconfig#3]
I installed this plugin as exactly described in README. However, the inverse search doesn't work. And I find no `nvim-texlabconfig.json` in `~/.cache/nvim`.
My neovim version is neovim-0.7-dev which has the `nvim-create-autogroup` api.

**Comment by f3fora** [comment]
You are right. I should have fix this.

**Comment by GirardR1006** [comment]
Reopining this issue as I am having the same problem. The file is not created. I have installed the plugin using packer.nvim.

Could you provide an example json file?
