### ISSUE TITLE
Error message when opening a tex file

### ISSUE THREAD

**Issue by jorgesca** [f3fora/nvim-texlabconfig#6]
Hi, I just discovered your plugin while looking at someone's config. When I open a tex file I get an error message:

>Error detected while processing FileType Autocommands for "tex":
Error executing lua callback: ...acker/start/nvim-texlabconfig/lua/texlabconfig/utils.lua:7: bad argument #1 to 'fs_open' (string expected, got nil)
stack traceback:
        [C]: in function 'fs_open'
        ...acker/start/nvim-texlabconfig/lua/texlabconfig/utils.lua:7: in function 'file_exists'
        ...acker/start/nvim-texlabconfig/lua/texlabconfig/cache.lua:65: in function 'read'
        ...acker/start/nvim-texlabconfig/lua/texlabconfig/cache.lua:26: in function 'add_servernames'
        ...acker/start/nvim-texlabconfig/lua/texlabconfig/cache.lua:87: in function <...acker/start/nvim-texlabconfig/lua/texlabconfig/cache.lua:86>
Press ENTER or type command to continue

I got he error above with my full config and also with a minimal init.lua that I created to check if my config was the source of the problem. I attach the minimal init.lua. 
Can you provide any hint about the problem? I can't tell if it is harmless or not, as I am just trying to set a working environment for editing latex documents and I don't know what to expect.

**Comment by jorgesca** [comment]
Minimal init.lua follows:

`local fn = vim.fn
local install_path = fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
	packer_bootstrap = fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', install_path})
end

return require('packer').startup(function(use)
	-- My plugins here
	-- use 'foo1/bar1.nvim'
	-- use 'foo2/bar2.nvim'
	use 'wbthomason/packer.nvim' -- Package manager
	use 'neovim/nvim-lspconfig' -- Configurations for Nvim LSP
	use({
		'f3fora/nvim-texlabconfig',
		config = function()
			require('texlabconfig').setup(config)
		end,
		-- ft = { 'tex', 'bib' }, -- for lazy loading
		run = 'go build'
		-- run = 'go build -o ~/.bin/' if e.g. ~/.bin/ is in $PATH
	})  -- Automatically set up your configuration after cloning packer.nvim
	-- Put this at the end after all plugins
	if packer_bootstrap then
		require('packer').sync()
	end
end)
`
I let packer bootstrap itself and sync the plugins. I have the executable available at ~/bin (in PATH)

**Comment by f3fora** [comment]
Should be fixed.

**Comment by jorgesca** [comment]
> Should be fixed.

Thanks, the error went away!
