### ISSUE TITLE
MacOS default cache path

### ISSUE THREAD

**Issue by mathjiajia** [f3fora/nvim-texlabconfig#7]
I am using this plugin on macOS with skim: `go build` + default configs.

skim settings:
Preset: `Custom`
Command: `$HOME/.local/share/nvim/site/pack/paqs/start/nvim-texlabconfig/nvim-texlabconfig`
Arguments: `-file '%file' -line %line`

After running the binary file, the terminal output is
```
$HOME/.local/share/nvim/site/pack/paqs/start/nvim-texlabconfig/nvim-texlabconfig
2022/07/18 23:06:57 Flags are required
```

could you have some help? Thank you in advance.

**Comment by f3fora** [comment]
click, where? Do you press also the right combination of keys? I do not use `skim`, but someone discusses this [here]( https://github.com/f3fora/nvim-texlabconfig/issues/2#issuecomment-1074566415).

`nvim-texlabconfig -file '/path/to/open/tex-file.tex' -line 1` should move the cursor to line 1.

**Comment by mathjiajia** [comment]
The link you mentioned is my early comment, before using the binary file.
By click I means `cmd` + `shift` + `click` on the pdf file in skim,
which works well in the past.

Using this command `nvim-texlabconfig -file '/path/to/open/tex-file.tex' -line 1` I got:
```
2022/07/18 23:33:57 Error when opening file: open /Users/jia/Library/Caches/nvim/nvim-texlabconfig.json: no such file or directory
```

It seems the `cache` directory is wrong, which should be `$HOME/.cache/nvim/nvim-texlabconfig.json`

Updated:
copy the `nvim-texlabconfig.json` file to `$HOME/Library/Caches/nvim/nvim-texlabconfig.json`
then it works.
I think that is the problem, i.e., the cache file location is not correct.

**Comment by f3fora** [comment]
You can use:

`nvim-texlabconfig -file '%f' -line %l -cache_root /path/to/cache_root/`

What is the output of `:echo stdpath('cache')` on Mac?

**Comment by mathjiajia** [comment]
That is a better workaround. Thank you.

The output of `:echo stdpath('cache')` on my computer is `/Users/jia/.cache/nvim`,
which implies in general it is `/Users/username/.cache/nvim` or `$HOME/.cache/nvim`.

**Comment by mathjiajia** [comment]
It seems that `XDG_CACHE_HOME` is `~/Library/Caches/AppName/` on macOS.
This will cause some problems.

**Comment by S1M0N38** [comment]
Hi, my setup is pretty much identical to @mathjiajia:
- Mac Intel Core, MacOS Big Sur
- Skim, Version 1.6.11 (141)
- Neovim  0.8.0-dev-2180-gf1c01e5f9
- in my _.zshenv_: `export XDG_CACHE_HOME="$HOME/.cache"`

I face the same problem. Right now I think that a good workaround is to create a soft link at _$HOME/Library/Caches/nvim/nvim-texlabconfig.json_ that points to _$HOME/.cache/nvim/nvim-texlabconfig.json_, i.e.
```bash
ln -s $HOME/.cache/nvim/nvim-texlabconfig.json $HOME/Library/Caches/nvim/nvim-texlabconfig.json
```

As @mathjiajia pointed out I think that there is some problem with XDG path on mac (maybe due to [xdg](https://github.com/adrg/xdg) go module). Now that we know the probable cause of the problem, the issue title should be more descriptive.

**Comment by f3fora** [comment]
A flag to set the cache file path actually exists. However, I am aware that this can be annoying for macOS users.

Neovim has chosen to use XDG paths also for macOS. neovim/neovim#19544.

[xdg](https://github.com/adrg/xdg) uses the [Standard Directories](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6) guidelines for macOS.

To fix this issue, there are some alternatives:

1. write a xdg equivalent library for lua
1. write a `stdpath` equivalent function in go
1. say explicitly in the docs to use the flag `-cache_path` in macOS

What do you think?

**Comment by S1M0N38** [comment]
I think that the third option is the simplest one. Just make it clear in the docs should be enough.

**Comment by mathjiajia** [comment]
> I think that the third option is the simplest one. Just make it clear in the docs should be enough.

Agree.
