### ISSUE TITLE
Attempt to index field 'cmd' (a function value)

### ISSUE THREAD

**Issue by Madoshakalaka** [f3fora/nvim-texlabconfig#8]
open a tex file and texlabconfig errors out:
```
packer.nvim: Error running config for nvim-texlabconfig: ...p
acker/opt/nvim-texlabconfig/lua/texlabconfig/config.lua:7: at
tempt to index field 'cmd' (a function value)
```

The line is at: 
https://github.com/f3fora/nvim-texlabconfig/blob/ca78e56ed5d95ea63121c374f3cfa145e7b20fd8/lua/texlabconfig/config.lua#L7

Committed by 3572f36bd2cfb6366806a667d66aaee8f69ed889

**Comment by f3fora** [comment]
If your nvim version is 0.7 use tag 0.2. 
If your nvim version is 0.8 use master branch.

**Comment by Madoshakalaka** [comment]
Thanks! I was on 0.7.2. I upgraded to 0.8 and the problem is fixed.
