### ISSUE TITLE
"config = function() ... end" required?

### ISSUE THREAD

**Issue by S1M0N38** [f3fora/nvim-texlabconfig#9]
I'm using [LunarVim](https://www.lunarvim.org/) which under the hood use Packer as plugin manager. It seems that the line
```lua
config = function() require('texlabconfig').setup() end
``` 
is required even though there is no need to specify custom config. If this line is not included the file `nvim-texlabconfig.json` is not written, hence this whole plugin stop working (I check the `require("texlabconfig.config").get().cache_root` directory). If I include this line everything run smoothly.

Did you experience the same issue on a vanilla neovim configuration?

**Comment by f3fora** [comment]
Yes. Read [Installation](https://github.com/f3fora/nvim-texlabconfig#installation) and [Configuration](https://github.com/f3fora/nvim-texlabconfig#configuration).

**Comment by S1M0N38** [comment]
Now that you point it out it's clear. On the other hand there are plugins that does not require `config` (e.g. colorscheme), so I think that should be make abundantly clear that that line is required (I've submitted a PR).
